# Generated by Django 5.0.7 on 2024-07-27 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='query_text',
            field=models.CharField(max_length=255),
        ),
    ]
