# Generated by Django 5.0.7 on 2024-08-07 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_query_query_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='query',
            old_name='timestamp',
            new_name='created_at',
        ),
    ]
